################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ Spanish language ##################
[es]
languageName = "Español"
languageCode = "es"
contentDir = "content/spanish"
weight = 2
